name: immortalwrt-24.10-docker-x86

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    uses: ./.github/workflows/_build-openwrt.yml
    with:
      source_url: https://github.com/immortalwrt/immortalwrt
      source_branch: openwrt-24.10
      target_board: x86
      target_subtarget: '64'
      config_file: configs/immortalwrt_24.10_docker_x86.config
      diy_part1: scripts/sh/immortalwrt_diy-part1.sh
      diy_part2: scripts/immortalwrt_24.10_x86.sh
      firmware_tag: immortalwrt-24.10-docker-x86
      firmware_pattern: '*squashfs-combined*.img.gz'
      firmware_description: with Docker
      default_ip: 192.168.15.1
      notify_wechat: false
      notify_telegram: false
    secrets: inherit
